### ISSUE TITLE
Adding entries blank screen

### ISSUE THREAD

**Issue by rauwebieten** [page-8/craft-manytomany#36] opened 2020-12-23 11:40 UTC
When editing an entry, and clicking the "add entry" button. The modal body table is empty.

I only have this problem when using relations where the section of the original field and the section of the manytomany field are the same section.

When I use the same field between different sections, the field works as intended.

**Comment by engram-design** [comment] 2022-11-24 01:29
Duplicate of https://github.com/verbb/many-to-many/issues/35 

Doesn't seem to be an issue anymore in the latest Craft versions, if you're still having the issue, let me know!

**Closed as completed by engram-design** 2022-11-24 01:29 UTC
